# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SMART Corporation
email: info@SMART-Corporation.com
description: > # this means to ignore newlines until "baseurl:"
  Some note to go here!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: SMART Corporation
address_line: 8 Fairlawn Ln, Suite 1-101, Lexington, MA 02420-2728, USA
telephone_number: +1.781.266.2004
fax_number: +1.555.555.5555
company_email: info@SMART-Corporation.com
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2944.283315714017!2d-71.19454598472583!3d42.442987679181336!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e39df875856f09%3A0x96423ac9bb4b9a9!2sSMART%20Corporation!5e0!3m2!1sen!2sus!4v1659290723527!5m2!1sen!2sus

# Social Link
facebook_link: http://www.facebook.com
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-responsive-image

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
